version: '3.1'
services:
  app:
    container_name: happy-budget
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    restart: always